language:
    - go

go:
    - 1.4

before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
    - go get github.com/smartystreets/goconvey/convey
    - go get gopkg.in/alecthomas/kingpin.v1

script:
    - ./covergen.sh
    - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
